version: '2'
services:

  nginx:
    restart: always
    container_name: keyserver-nginx
    build: docker/nginx
    ports:
      - "8085:8085"
    volumes:
      - ./src:/src
      - ./logs/nginx/:/logs
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    links:
      - php

  php:
    restart: always
    container_name: keyserver-php
    build: docker/php
    volumes:
      - ./src:/src
      - ./logs:/logs
    env_file:
      - ./.env

  redis:
    restart: always
    container_name: keyserver-redis
    image: redis:3.2
