version: '2'
services:

  php-fpm:
    restart: always
    container_name: smartmoney-keys-fpm
    image: smartmoney/keys/fpm
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./logs/php-fpm/:/logs
    env_file:
      - .env
    environment:
      LOG_LEVEL: ERROR

  nginx:
    restart: always
    container_name: smartmoney-keys-nginx
    image: smartmoney/keys/nginx
    build: docker/nginx
    ports:
      - "8085:80"
    volumes:
      - ./app:/app
      - ./logs/nginx/:/logs
    links:
      - php-fpm
