version: '2'
services:

  php-fpm:
    restart: always
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./docker/php-fpm/app:/app
      - ./logs/php-fpm/:/logs
    links:
      - riak

  nginx:
    restart: always
    build: docker/nginx
    ports:
      - "8085:80"
    volumes:
      - ./docker/php-fpm/app:/app
      - ./logs/nginx/:/logs
    links:
      - php-fpm

  riak:
    restart: always
    build: docker/riak
    volumes:
      - ./storage/riak:/var/lib/riak
      - ./logs/riak/:/logs
